// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCqKfvPASEKjoJcUdTJKNKsVAvps0qMvc',
    appId: '1:488065606118:web:bab0c098443cf19749f627',
    messagingSenderId: '488065606118',
    projectId: 'umkm-vanker',
    authDomain: 'umkm-vanker.firebaseapp.com',
    storageBucket: 'umkm-vanker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADKpq22mu91WZ7mwlVEIrfvDeCZ7z5KqY',
    appId: '1:488065606118:android:b612acb48ed187f449f627',
    messagingSenderId: '488065606118',
    projectId: 'umkm-vanker',
    storageBucket: 'umkm-vanker.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCqKfvPASEKjoJcUdTJKNKsVAvps0qMvc',
    appId: '1:488065606118:web:03518c74cbfc1edc49f627',
    messagingSenderId: '488065606118',
    projectId: 'umkm-vanker',
    authDomain: 'umkm-vanker.firebaseapp.com',
    storageBucket: 'umkm-vanker.firebasestorage.app',
  );
}
