// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmJDutFCaXBHhFhEsx2P8YlSxCtDhKlSc',
    appId: '1:780707182110:web:40eda384b7c8035320a00f',
    messagingSenderId: '780707182110',
    projectId: 'umkm-go-cdfd9',
    authDomain: 'umkm-go-cdfd9.firebaseapp.com',
    storageBucket: 'umkm-go-cdfd9.firebasestorage.app',
    measurementId: 'G-9XGTS7D7W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8PqeRp3lX7bShjZ1HVNfXCjjnBwFDbNE',
    appId: '1:780707182110:android:e9560c12e52a361420a00f',
    messagingSenderId: '780707182110',
    projectId: 'umkm-go-cdfd9',
    storageBucket: 'umkm-go-cdfd9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmJDutFCaXBHhFhEsx2P8YlSxCtDhKlSc',
    appId: '1:780707182110:web:f5080e1a04077aaa20a00f',
    messagingSenderId: '780707182110',
    projectId: 'umkm-go-cdfd9',
    authDomain: 'umkm-go-cdfd9.firebaseapp.com',
    storageBucket: 'umkm-go-cdfd9.firebasestorage.app',
    measurementId: 'G-MLJ489PVWD',
  );
}
